git push origin --delete dependabot/bundler/bootstrap101/bootstrap/nokogiri-1.13.6
git push origin --delete dependabot/npm_and_yarn/bootstrap101/bootstrap/acorn-5.7.4
git push origin --delete dependabot/npm_and_yarn/bootstrap101/bootstrap/ajv-6.12.6
git push origin --delete dependabot/npm_and_yarn/bootstrap101/bootstrap/browserslist-4.16.6
git push origin --delete dependabot/npm_and_yarn/bootstrap101/bootstrap/browserslist-4.20.4
git push origin --delete dependabot/npm_and_yarn/bootstrap101/bootstrap/browserslist-4.21.1
git push origin --delete dependabot/npm_and_yarn/bootstrap101/bootstrap/color-string-1.6.0
git push origin --delete dependabot/npm_and_yarn/bootstrap101/bootstrap/color-string-1.9.1
git push origin --delete dependabot/npm_and_yarn/bootstrap101/bootstrap/decompress-4.2.1
git push origin --delete dependabot/npm_and_yarn/bootstrap101/bootstrap/eslint-utils-1.4.3
git push origin --delete dependabot/npm_and_yarn/bootstrap101/bootstrap/hosted-git-info-2.8.9
git push origin --delete dependabot/npm_and_yarn/bootstrap101/bootstrap/ini-1.3.7
git push origin --delete dependabot/npm_and_yarn/bootstrap101/bootstrap/ini-1.3.8
git push origin --delete dependabot/npm_and_yarn/bootstrap101/bootstrap/jquery-3.5.0
git push origin --delete dependabot/npm_and_yarn/bootstrap101/bootstrap/lodash-4.17.21
git push origin --delete dependabot/npm_and_yarn/bootstrap101/bootstrap/node-sass-4.14.1
git push origin --delete dependabot/npm_and_yarn/bootstrap101/bootstrap/path-parse-1.0.7
git push origin --delete dependabot/npm_and_yarn/bootstrap101/bootstrap/pathval-1.1.1
git push origin --delete dependabot/npm_and_yarn/bootstrap101/bootstrap/postcss-7.0.36
git push origin --delete dependabot/npm_and_yarn/bootstrap101/bootstrap/y18n-3.2.2
git push origin --delete dependabot/npm_and_yarn/react/a05/terser-5.15.0
git push origin --delete dependabot/npm_and_yarn/react/a06/terser-5.15.0
git push origin --delete dependabot/npm_and_yarn/react/a07/terser-5.15.0
git push origin --delete dependabot/npm_and_yarn/react/a08/terser-5.15.0
git push origin --delete dependabot/npm_and_yarn/react/a09/terser-5.15.0
git push origin --delete dependabot/npm_and_yarn/react/a10/terser-5.15.0
git push origin --delete dependabot/npm_and_yarn/react/a11/terser-5.15.0
git push origin --delete dependabot/npm_and_yarn/react2/terser-5.15.0
git push origin --delete dependabot/npm_and_yarn/vue/chat/firechat/ajv-6.12.6
git push origin --delete dependabot/npm_and_yarn/vue/chat/firechat/dns-packet-1.3.4
git push origin --delete dependabot/npm_and_yarn/vue/chat/firechat/elliptic-6.5.4
git push origin --delete dependabot/npm_and_yarn/vue/chat/firechat/hosted-git-info-2.8.9
git push origin --delete dependabot/npm_and_yarn/vue/chat/firechat/http-proxy-1.18.1
git push origin --delete dependabot/npm_and_yarn/vue/chat/firechat/lodash-4.17.21
git push origin --delete dependabot/npm_and_yarn/vue/chat/firechat/path-parse-1.0.7
git push origin --delete dependabot/npm_and_yarn/vue/chat/firechat/webpack-dev-server-3.1.11
git push origin --delete dependabot/npm_and_yarn/vue/chat/firechat/websocket-extensions-0.1.4
git push origin --delete dependabot/npm_and_yarn/vue/chat/firechat/y18n-3.2.2
