import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";

export default function Home() {
	const [response, setResponse] = useState("");

	function handleGetAll() {
		fetch("/api/users", {
			method: "GET",
			headers: {
				"Content-Type": "application/json"
			}
		})
			.then((response) => response.json())
			.then((data) => {
				console.log(data);
				setResponse(JSON.stringify(data));
			})
			.catch((error) => {
				console.log(error);
			});
	}

	function handleGetSingle() {
		fetch("/api/users/2", {
			method: "GET",
			headers: {
				"Content-Type": "application/json"
			}
		})
			.then((response) => response.json())
			.then((data) => {
				console.log(data);
				setResponse(JSON.stringify(data));
			})
			.catch((error) => {
				console.log(error);
			});
    }

	function handlePost() {
		fetch("/api/users", {
			method: "POST",
			headers: {
				"Content-Type": "application/json"
			}
		})
			.then((response) => response.json())
			.then((data) => {
				console.log(data);
				setResponse(JSON.stringify(data));
			})
			.catch((error) => {
				console.log(error);
			});    
  }

	function handlePut() {
		fetch("/api/users/2", {
			method: "PUT",
			headers: {
				"Content-Type": "application/json"
			}
		})
			.then((response) => response.json())
			.then((data) => {
				console.log(data);
				setResponse(JSON.stringify(data));
			})
			.catch((error) => {
				console.log(error);
			});    
  }

	function handleDelete() {
		fetch("/api/users/2", {
			method: "DELETE",
			headers: {
				"Content-Type": "application/json"
			}
		})
			.then((response) => response.json())
			.then((data) => {
				console.log(data);
				setResponse(JSON.stringify(data));
			})
			.catch((error) => {
				console.log(error);
			});      }

	return (
		<>
			<Head>
				<title>Testing API</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<div className={styles.description}>
					<h2>Testing API routes</h2>
					<p>
						<b>Result</b> <br />
						{response}
					</p>
					<p>
						GET ALL <br />
						<code>https://reqres.in/api/users/</code>
						<br />
						<button onClick={handleGetAll}>GET ALL</button>
					</p>
					<p>
						GET SINGLE <br />
						<code>https://reqres.in/api/users/1</code>
						<br />
						<button onClick={handleGetSingle}>GET Single</button>
					</p>
					<p>
						POST <br />
						<code>https://reqres.in/api/users/</code>
						<br />
						<button onClick={handlePost}>POST</button>
					</p>
					<p>
						PUT <br />
						<code>https://reqres.in/api/users/</code>
						<br />
						<button onClick={handlePut}>PUT</button>
					</p>
					<p>
						DELETE <br />
						<code>https://reqres.in/api/users/1</code>
						<br />
						<button onClick={handleDelete}>DELETE</button>
					</p>
					<h3>
						<a href="https://reqres.in/">https://reqres.in/</a>
					</h3>
				</div>
			</main>
		</>
	);
}
